"""Static constants for VideOCR Recreated, extracted from the legacy VideOCR.py GUI."""

from __future__ import annotations

import sys

# --- OCR engines ---
OCR_ENGINES = ['PaddleOCR (Det. + Rec.)',
 'PaddleOCR (Det.) + Google Lens (Rec.)',
 'EasyOCR DirectML (AMD GPU)',
 'ONNX Runtime DirectML (AMD GPU Experimental)']

# --- Language lists (name, code) ---
PADDLEOCR_LANGUAGES_LIST = [('Abaza', 'abq'),
 ('Adyghe', 'ady'),
 ('Afrikaans', 'af'),
 ('Albanian', 'sq'),
 ('Angika', 'ang'),
 ('Arabic', 'ar'),
 ('Avar', 'ava'),
 ('Azerbaijani', 'az'),
 ('Baluchi', 'bal'),
 ('Bashkir', 'ba'),
 ('Basque', 'eu'),
 ('Belarusian', 'be'),
 ('Bhojpuri', 'bho'),
 ('Bihari', 'bh'),
 ('Bosnian', 'bs'),
 ('Bulgarian', 'bg'),
 ('Buryat', 'bua'),
 ('Catalan', 'ca'),
 ('Chechen', 'che'),
 ('Chinese & English', 'ch'),
 ('Chinese Traditional', 'chinese_cht'),
 ('Chuvash', 'cv'),
 ('Croatian', 'hr'),
 ('Czech', 'cs'),
 ('Danish', 'da'),
 ('Dargwa', 'dar'),
 ('Dutch', 'nl'),
 ('English', 'en'),
 ('Estonian', 'et'),
 ('Finnish', 'fi'),
 ('French', 'fr'),
 ('Galician', 'gl'),
 ('Georgian', 'ka'),
 ('German', 'german'),
 ('Goan Konkani', 'gom'),
 ('Greek', 'el'),
 ('Haryanvi', 'bgc'),
 ('Hindi', 'hi'),
 ('Hungarian', 'hu'),
 ('Icelandic', 'is'),
 ('Indonesian', 'id'),
 ('Ingush', 'inh'),
 ('Irish', 'ga'),
 ('Italian', 'it'),
 ('Japanese', 'japan'),
 ('Kabardian', 'kbd'),
 ('Kalmyk', 'xal'),
 ('Karakalpak', 'kaa'),
 ('Kazakh', 'kk'),
 ('Komi', 'kv'),
 ('Korean', 'korean'),
 ('Kurdish', 'ku'),
 ('Kyrgyz', 'ky'),
 ('Lak', 'lbe'),
 ('Latin', 'la'),
 ('Latvian', 'lv'),
 ('Lezghian', 'lez'),
 ('Lithuanian', 'lt'),
 ('Luxembourgish', 'lb'),
 ('Macedonian', 'mk'),
 ('Magahi', 'mah'),
 ('Maithili', 'mai'),
 ('Malay', 'ms'),
 ('Maltese', 'mt'),
 ('Maori', 'mi'),
 ('Marathi', 'mr'),
 ('Meadow Mari', 'mhr'),
 ('Moldovan', 'mo'),
 ('Mongolian', 'mn'),
 ('Nagpuri', 'sck'),
 ('Nepali', 'ne'),
 ('Newari', 'new'),
 ('Norwegian', 'no'),
 ('Occitan', 'oc'),
 ('Ossetian', 'os'),
 ('Pali', 'pi'),
 ('Pashto', 'ps'),
 ('Persian', 'fa'),
 ('Polish', 'pl'),
 ('Portuguese', 'pt'),
 ('Quechua', 'qu'),
 ('Romanian', 'ro'),
 ('Romansh', 'rm'),
 ('Russian', 'ru'),
 ('Sakha', 'sah'),
 ('Sanskrit', 'sa'),
 ('Serbian(cyrillic)', 'rs_cyrillic'),
 ('Serbian(latin)', 'rs_latin'),
 ('Sindhi', 'sd'),
 ('Slovak', 'sk'),
 ('Slovenian', 'sl'),
 ('Spanish', 'es'),
 ('Swahili', 'sw'),
 ('Swedish', 'sv'),
 ('Tabassaran', 'tab'),
 ('Tagalog', 'tl'),
 ('Tajik', 'tg'),
 ('Tamil', 'ta'),
 ('Tatar', 'tt'),
 ('Telugu', 'te'),
 ('Thai', 'th'),
 ('Turkish', 'tr'),
 ('Tuvan', 'tyv'),
 ('Udmurt', 'udm'),
 ('Ukrainian', 'uk'),
 ('Urdu', 'ur'),
 ('Uyghur', 'ug'),
 ('Uzbek', 'uz'),
 ('Vietnamese', 'vi'),
 ('Welsh', 'cy')]

GOOGLE_LENS_LANGUAGES_LIST = [('Afrikaans', 'af'),
 ('Albanian', 'sq'),
 ('Arabic', 'ar'),
 ('Armenian', 'hy'),
 ('Belarusian', 'be'),
 ('Bengali', 'bn'),
 ('Bulgarian', 'bg'),
 ('Catalan', 'ca'),
 ('Chinese', 'zh'),
 ('Croatian', 'hr'),
 ('Czech', 'cs'),
 ('Danish', 'da'),
 ('Dutch', 'nl'),
 ('English', 'en'),
 ('Estonian', 'et'),
 ('Filipino', 'fil'),
 ('Finnish', 'fi'),
 ('French', 'fr'),
 ('German', 'de'),
 ('Greek', 'el'),
 ('Gujarati', 'gu'),
 ('Hebrew', 'iw'),
 ('Hindi', 'hi'),
 ('Hungarian', 'hu'),
 ('Icelandic', 'is'),
 ('Indonesian', 'id'),
 ('Italian', 'it'),
 ('Japanese', 'ja'),
 ('Kannada', 'kn'),
 ('Khmer', 'km'),
 ('Korean', 'ko'),
 ('Lao', 'lo'),
 ('Latvian', 'lv'),
 ('Lithuanian', 'lt'),
 ('Macedonian', 'mk'),
 ('Malay', 'ms'),
 ('Malayalam', 'ml'),
 ('Marathi', 'mr'),
 ('Nepali', 'ne'),
 ('Norwegian', 'no'),
 ('Persian', 'fa'),
 ('Polish', 'pl'),
 ('Portuguese', 'pt'),
 ('Punjabi', 'pa'),
 ('Romanian', 'ro'),
 ('Russian', 'ru'),
 ('Russian (PETR1708)', 'ru-PETR1708'),
 ('Serbian', 'sr'),
 ('Serbian (Latin)', 'sr-Latn'),
 ('Slovak', 'sk'),
 ('Slovenian', 'sl'),
 ('Spanish', 'es'),
 ('Swedish', 'sv'),
 ('Tagalog', 'tl'),
 ('Tamil', 'ta'),
 ('Telugu', 'te'),
 ('Thai', 'th'),
 ('Turkish', 'tr'),
 ('Ukrainian', 'uk'),
 ('Vietnamese', 'vi'),
 ('Yiddish', 'yi'),
 ('Amharic', 'am'),
 ('Ancient Greek', 'grc'),
 ('Assamese', 'as'),
 ('Azerbaijani', 'az'),
 ('Azerbaijani (Cyrl)', 'az-Cyrl'),
 ('Basque', 'eu'),
 ('Bosnian', 'bs'),
 ('Burmese', 'my'),
 ('Cebuano', 'ceb'),
 ('Cherokee', 'chr'),
 ('Dhivehi', 'dv'),
 ('Dzonkha', 'dz'),
 ('Esperanto', 'eo'),
 ('Galician', 'gl'),
 ('Georgian', 'ka'),
 ('Haitian Creole', 'ht'),
 ('Irish', 'ga'),
 ('Javanese', 'jv'),
 ('Kazakh', 'kk'),
 ('Kirghiz', 'ky'),
 ('Latin', 'la'),
 ('Maltese', 'mt'),
 ('Mongolian', 'mn'),
 ('Oriya', 'or'),
 ('Pashto', 'ps'),
 ('Sanskrit', 'sa'),
 ('Sinhala', 'si'),
 ('Swahili', 'sw'),
 ('Syriac', 'syr'),
 ('Tibetan', 'bo'),
 ('Tigirinya', 'ti'),
 ('Urdu', 'ur'),
 ('Uzbek', 'uz'),
 ('Uzbek (Cyrl)', 'uz-Cyrl'),
 ('Welsh', 'cy'),
 ('Zulu', 'zu'),
 ('Acehnese', 'ace'),
 ('Acholi', 'ach'),
 ('Adangme', 'ada'),
 ('Akan', 'ak'),
 ('Algonquinian', 'alg'),
 ('Araucanian/Mapuche', 'arn'),
 ('Asturian', 'ast'),
 ('Athabaskan', 'ath'),
 ('Aymara', 'ay'),
 ('Balinese', 'ban'),
 ('Bambara', 'bm'),
 ('Bantu', 'bnt'),
 ('Bashkir', 'ba'),
 ('Batak', 'btk'),
 ('Bemba', 'bem'),
 ('Bikol', 'bik'),
 ('Bislama', 'bi'),
 ('Breton', 'br'),
 ('Chechen', 'ce'),
 ('Chinese (Simplified)', 'zh-Hans'),
 ('Chinese (Traditional)', 'zh-Hant'),
 ('Chinese (Hong Kong)', 'zh-Hant-HK'),
 ('Choctaw', 'cho'),
 ('Chuvash', 'cv'),
 ('Cree', 'cr'),
 ('Creek', 'mus'),
 ('Crimean Tatar', 'crh'),
 ('Dakota', 'dak'),
 ('Duala', 'dua'),
 ('Efik', 'efi'),
 ('English (British)', 'en-GB'),
 ('Ewe', 'ee'),
 ('Faroese', 'fo'),
 ('Fijian', 'fj'),
 ('Fon', 'fon'),
 ('French (Canadian)', 'fr-CA'),
 ('Fulah', 'ff'),
 ('Ga', 'gaa'),
 ('Ganda', 'lg'),
 ('Gayo', 'gay'),
 ('Gilbertese', 'gil'),
 ('Gothic', 'got'),
 ('Guarani', 'gn'),
 ('Hausa', 'ha'),
 ('Hawaiian', 'haw'),
 ('Herero', 'hz'),
 ('Hiligaynon', 'hil'),
 ('Iban', 'iba'),
 ('Igbo', 'ig'),
 ('Iloko', 'ilo'),
 ('Kabyle', 'kab'),
 ('Kachin', 'kac'),
 ('Kalaallisut', 'kl'),
 ('Kamba', 'kam'),
 ('Kanuri', 'kr'),
 ('Kara-Kalpak', 'kaa'),
 ('Khasi', 'kha'),
 ('Kikuyu', 'ki'),
 ('Kinyarwanda', 'rw'),
 ('Komi', 'kv'),
 ('Kongo', 'kg'),
 ('Kosraean', 'kos'),
 ('Kuanyama', 'kj'),
 ('Lingala', 'ln'),
 ('Low German', 'nds'),
 ('Lozi', 'loz'),
 ('Luba-Katanga', 'lu'),
 ('Luo', 'luo'),
 ('Madurese', 'mad'),
 ('Malagasy', 'mg'),
 ('Mandingo', 'man'),
 ('Manx', 'gv'),
 ('Maori', 'mi'),
 ('Marshallese', 'mh'),
 ('Mende', 'men'),
 ('Middle English', 'enm'),
 ('Middle High German', 'gmh'),
 ('Minangkabau', 'min'),
 ('Mohawk', 'moh'),
 ('Mongo', 'lol'),
 ('Nahuatl', 'nah'),
 ('Navajo', 'nv'),
 ('Ndonga', 'ng'),
 ('Niuean', 'niu'),
 ('North Ndebele', 'nd'),
 ('Northern Sotho', 'nso'),
 ('Nyanja', 'ny'),
 ('Nyankole', 'nyn'),
 ('Nyasa Tonga', 'tog'),
 ('Nzima', 'nzi'),
 ('Occitan', 'oc'),
 ('Ojibwa', 'oj'),
 ('Old English', 'ang'),
 ('Old French', 'fro'),
 ('Old High German', 'goh'),
 ('Old Norse', 'non'),
 ('Old Provencal', 'pro'),
 ('Ossetic', 'os'),
 ('Pampanga', 'pam'),
 ('Pangasinan', 'pag'),
 ('Papiamento', 'pap'),
 ('Portuguese (European)', 'pt-PT'),
 ('Quechua', 'qu'),
 ('Romansh', 'rm'),
 ('Romany', 'rom'),
 ('Rundi', 'rn'),
 ('Sakha', 'sah'),
 ('Samoan', 'sm'),
 ('Sango', 'sg'),
 ('Scots', 'sco'),
 ('Scottish Gaelic', 'gd'),
 ('Shona', 'sn'),
 ('Songhai', 'son'),
 ('Southern Sotho', 'st'),
 ('Spanish (Latin American)', 'es-419'),
 ('Sundanese', 'su'),
 ('Swati', 'ss'),
 ('Tahitian', 'ty'),
 ('Tajik', 'tg'),
 ('Tatar', 'tt'),
 ('Temne', 'tem'),
 ('Tongan', 'to'),
 ('Tsonga', 'ts'),
 ('Tswana', 'tn'),
 ('Turkmen', 'tk'),
 ('Udmurt', 'udm'),
 ('Venda', 've'),
 ('Votic', 'vot'),
 ('Western Frisian', 'fy'),
 ('Wolof', 'wo'),
 ('Xhosa', 'xh'),
 ('Yoruba', 'yo'),
 ('Zapotec', 'zap')]

EASYOCR_LANGUAGES_LIST = [('English', 'en'),
 ('Japanese + English', 'japan'),
 ('Korean + English', 'korean'),
 ('Chinese Simplified + English', 'ch'),
 ('Chinese Traditional + English', 'chinese_cht'),
 ('German + English', 'german'),
 ('French + English', 'fr'),
 ('Spanish + English', 'es'),
 ('Italian + English', 'it'),
 ('Portuguese + English', 'pt'),
 ('Russian + English', 'ru'),
 ('Arabic + English', 'ar'),
 ('Indonesian + English', 'id'),
 ('Thai + English', 'th'),
 ('Vietnamese + English', 'vi')]

# --- Language code maps ---
EASY_TO_ISO_MAP = {'ch': 'zh', 'chinese_cht': 'zh', 'german': 'de', 'japan': 'ja', 'korean': 'ko'}

PADDLE_TO_ISO_MAP = {'ang': 'anp',
 'ava': 'av',
 'ch': 'zh',
 'che': 'ce',
 'chinese_cht': 'zh',
 'german': 'de',
 'japan': 'ja',
 'korean': 'ko',
 'mah': 'mag',
 'mo': 'ro',
 'rs_cyrillic': 'sr',
 'rs_latin': 'sr'}

# --- Subtitle position / alignment ---
SUBTITLE_POSITIONS_LIST = [('pos_center', 'center'),
 ('pos_left', 'left'),
 ('pos_right', 'right'),
 ('pos_any', 'any')]

SUBTITLE_ALIGNMENT_LIST = [('align_bottom_center', 'bottom-center'),
 ('align_bottom_left', 'bottom-left'),
 ('align_bottom_right', 'bottom-right'),
 ('align_top_center', 'top-center'),
 ('align_top_left', 'top-left'),
 ('align_top_right', 'top-right'),
 ('align_middle_center', 'middle-center'),
 ('align_middle_left', 'middle-left'),
 ('align_middle_right', 'middle-right')]

# --- Post-completion actions ---
POST_ACTION_KEYS_WINDOWS = ['action_none', 'action_sleep', 'action_hibernate', 'action_shutdown', 'action_lock']
POST_ACTION_KEYS_OTHER = ['action_none', 'action_sleep', 'action_shutdown']
if sys.platform == 'win32':
    POST_ACTION_KEYS = POST_ACTION_KEYS_WINDOWS
else:
    POST_ACTION_KEYS = POST_ACTION_KEYS_OTHER

DEFAULT_ACTION_TEXTS = {'action_hibernate': 'Hibernate',
 'action_lock': 'Lock',
 'action_none': 'Do Nothing',
 'action_shutdown': 'Shutdown',
 'action_sleep': 'Sleep'}

# --- GUI scaling ---
GUI_SCALING_LIST = [('system_default', 'System Default'),
 ('scale_1_0', '1.0'),
 ('scale_1_25', '1.25'),
 ('scale_1_5', '1.5'),
 ('scale_1_75', '1.75'),
 ('scale_2_0', '2.0')]
DEFAULT_GUI_SCALING = 'system_default'

# --- DirectML options ---
DIRECTML_AUTO_OPTION = 'Auto (recommended)'
DIRECTML_PERFORMANCE_PRESETS = [('Compatibility / Low VRAM', 'compatibility'),
 ('Balanced (recommended)', 'balanced'),
 ('Max AMD GPU Load', 'max'),
 ('Manual Grid Size', 'manual')]
DIRECTML_RECOGNITION_MODES = [('Stable Hybrid (recommended)', 'stable'),
 ('AMD Max Auto (try GPU recognition + fallback)', 'auto'),
 ('Experimental Full DirectML', 'experimental')]
DIRECTML_FRAME_SCAN_MODES = [('CPU SSIM (compatible)', 'cpu_ssim'),
 ('AMD DirectML SSIM (experimental)', 'directml_ssim'),
 ('AMD FFmpeg D3D11VA Decode + DirectML SSIM (prototype)', 'ffmpeg_d3d11va')]
ONNX_DIRECTML_TUNING_MODES = [('Low VRAM / safer', 'low_vram'),
 ('Balanced ONNX (recommended)', 'balanced'),
 ('Max Throughput / higher VRAM', 'max'),
 ('Manual Grid Size', 'manual')]

# --- Defaults ---
DEFAULT_OCR_ENGINE = 'PaddleOCR (Det. + Rec.)'
DEFAULT_SUBTITLE_LANGUAGE = 'English'
DEFAULT_SUBTITLE_POSITION = 'center'
DEFAULT_SUBTITLE_ALIGNMENT = 'bottom-center'
DEFAULT_TIME_START = '0:00'
DEFAULT_INTERNAL_SUBTITLE_POSITION = 'center'
DEFAULT_CONF_THRESHOLD = 75
DEFAULT_SIM_THRESHOLD = 80
DEFAULT_MAX_MERGE_GAP = 0.1
DEFAULT_MIN_SUBTITLE_DURATION = 0.2
DEFAULT_SSIM_THRESHOLD = 92
DEFAULT_OCR_IMAGE_MAX_WIDTH = 720
DEFAULT_FRAMES_TO_SKIP = 1
KEY_SEEK_STEP = 1

paddle_display_names = [lang[0] for lang in PADDLEOCR_LANGUAGES_LIST]
paddle_abbr_lookup = {name: abbr for name, abbr in PADDLEOCR_LANGUAGES_LIST}
lens_display_names = [lang[0] for lang in GOOGLE_LENS_LANGUAGES_LIST]
lens_abbr_lookup = {name: abbr for name, abbr in GOOGLE_LENS_LANGUAGES_LIST}
easyocr_display_names = [lang[0] for lang in EASYOCR_LANGUAGES_LIST]
easyocr_abbr_lookup = {name: abbr for name, abbr in EASYOCR_LANGUAGES_LIST}

DIRECTML_PERFORMANCE_DISPLAY = [name for name, _ in DIRECTML_PERFORMANCE_PRESETS]
DIRECTML_PERFORMANCE_TO_CLI = {name: value for name, value in DIRECTML_PERFORMANCE_PRESETS}
DIRECTML_PERFORMANCE_FROM_CLI = {value: name for name, value in DIRECTML_PERFORMANCE_PRESETS}
DIRECTML_RECOGNITION_DISPLAY = [name for name, _ in DIRECTML_RECOGNITION_MODES]
DIRECTML_RECOGNITION_TO_CLI = {name: value for name, value in DIRECTML_RECOGNITION_MODES}
DIRECTML_RECOGNITION_FROM_CLI = {value: name for name, value in DIRECTML_RECOGNITION_MODES}
DIRECTML_FRAME_SCAN_DISPLAY = [name for name, _ in DIRECTML_FRAME_SCAN_MODES]
DIRECTML_FRAME_SCAN_TO_CLI = {name: value for name, value in DIRECTML_FRAME_SCAN_MODES}
DIRECTML_FRAME_SCAN_FROM_CLI = {value: name for name, value in DIRECTML_FRAME_SCAN_MODES}
ONNX_DIRECTML_TUNING_DISPLAY = [name for name, _ in ONNX_DIRECTML_TUNING_MODES]
ONNX_DIRECTML_TUNING_TO_CLI = {name: value for name, value in ONNX_DIRECTML_TUNING_MODES}
ONNX_DIRECTML_TUNING_FROM_CLI = {value: name for name, value in ONNX_DIRECTML_TUNING_MODES}
